<?php

$mapBasemapDriver = env('FOTOMETRO_MAP_BASEMAP_DRIVER', 'raster');

if (! in_array($mapBasemapDriver, ['raster', 'style'], true)) {
    $mapBasemapDriver = 'raster';
}

return [
    'map' => [
        'basemap_driver' => $mapBasemapDriver,
        'style_url' => env('FOTOMETRO_MAP_STYLE_URL'),
        'raster_url' => blank(env('FOTOMETRO_MAP_RASTER_URL')) ? 'https://tile.openstreetmap.org/{z}/{x}/{y}.png' : env('FOTOMETRO_MAP_RASTER_URL'),
        'raster_tile_size' => blank(env('FOTOMETRO_MAP_RASTER_TILE_SIZE')) ? 256 : (int) env('FOTOMETRO_MAP_RASTER_TILE_SIZE'),
        'attribution' => env('FOTOMETRO_MAP_ATTRIBUTION', '© OpenStreetMap contributors'),
        'cache_ttl' => (int) env('FOTOMETRO_MAP_CACHE_TTL', 300),
        'center' => [
            'latitude' => (float) env('FOTOMETRO_MAP_CENTER_LATITUDE', 48.8566),
            'longitude' => (float) env('FOTOMETRO_MAP_CENTER_LONGITUDE', 2.3522),
            'zoom' => (float) env('FOTOMETRO_MAP_DEFAULT_ZOOM', 11.5),
            'max_zoom' => blank(env('FOTOMETRO_MAP_MAX_ZOOM')) ? 19 : (float) env('FOTOMETRO_MAP_MAX_ZOOM'),
        ],
    ],
    'photos' => [
        'disk' => env('FOTOMETRO_PHOTO_DISK', 'local'),
        'max_upload_mb' => (int) env('FOTOMETRO_PHOTO_MAX_UPLOAD_MB', 40),
        'batch_limit' => (int) env('FOTOMETRO_PHOTO_BATCH_LIMIT', 20),
        'exif_station_match_radius_meters' => (float) env('FOTOMETRO_PHOTO_EXIF_MATCH_RADIUS_METERS', 200),
        'manual_process_limit' => (int) env('FOTOMETRO_PHOTO_MANUAL_PROCESS_LIMIT', 5),
        'process_synchronously' => filter_var(env('FOTOMETRO_PHOTO_PROCESS_SYNCHRONOUSLY', false), FILTER_VALIDATE_BOOL),
        'web_max_width' => (int) env('FOTOMETRO_PHOTO_WEB_MAX_WIDTH', 2200),
        'thumbnail_width' => (int) env('FOTOMETRO_PHOTO_THUMBNAIL_WIDTH', 600),
        'web_quality' => (int) env('FOTOMETRO_PHOTO_WEB_QUALITY', 85),
        'thumbnail_quality' => (int) env('FOTOMETRO_PHOTO_THUMBNAIL_QUALITY', 82),
        'default_copyright_holder' => env('FOTOMETRO_PHOTO_COPYRIGHT_HOLDER', config('app.name', 'fotometro')),
        'default_copyright_notice' => env('FOTOMETRO_PHOTO_COPYRIGHT_NOTICE'),
        'default_license' => env('FOTOMETRO_PHOTO_DEFAULT_LICENSE', 'all_rights_reserved'),
        'default_credit_line' => env('FOTOMETRO_PHOTO_CREDIT_LINE'),
        'default_usage_terms' => env('FOTOMETRO_PHOTO_USAGE_TERMS'),
        'watermark' => [
            'enabled' => filter_var(env('FOTOMETRO_PHOTO_WATERMARK_ENABLED', false), FILTER_VALIDATE_BOOL),
            'text' => env('FOTOMETRO_PHOTO_WATERMARK_TEXT'),
            'position' => env('FOTOMETRO_PHOTO_WATERMARK_POSITION', 'bottom-right'),
            'opacity' => (float) env('FOTOMETRO_PHOTO_WATERMARK_OPACITY', 0.45),
        ],
    ],
    'idfm' => [
        'lines_url' => env('FOTOMETRO_IDFM_LINES_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/referentiel-des-lignes/records?limit=100'),
        'arrets_lignes_url' => env('FOTOMETRO_IDFM_ARRETS_LIGNES_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/arrets-lignes/records?limit=100'),
        'stop_areas_url' => env('FOTOMETRO_IDFM_STOP_AREAS_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/zones-d-arrets/exports/csv?limit=-1'),
        'stop_relations_url' => env('FOTOMETRO_IDFM_STOP_RELATIONS_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/relations/exports/csv?limit=-1'),
        'traces_url' => env('FOTOMETRO_IDFM_TRACES_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/traces-des-lignes-de-transport-en-commun-idfm/records?limit=100'),
        'gtfs_url' => env('FOTOMETRO_IDFM_GTFS_URL', 'https://data.iledefrance.fr/api/explore/v2.1/catalog/datasets/offre-horaires-tc-gtfs-idfm/records?limit=1'),
        'accesses_url' => env('FOTOMETRO_IDFM_ACCESSES_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/acces/exports/csv?limit=-1'),
        'access_relations_url' => env('FOTOMETRO_IDFM_ACCESS_RELATIONS_URL', 'https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/relations-acces/exports/csv?limit=-1'),
        'timeout' => (int) env('FOTOMETRO_IDFM_TIMEOUT', 30),
        'temp_dir' => env('FOTOMETRO_IDFM_TEMP_DIR', storage_path('app/idfm')),
        'import_accesses' => filter_var(env('FOTOMETRO_IDFM_IMPORT_ACCESSES', true), FILTER_VALIDATE_BOOL),
        'deactivate_absent' => filter_var(env('FOTOMETRO_IDFM_DEACTIVATE_ABSENT', true), FILTER_VALIDATE_BOOL),
    ],
    'line_orientation' => [
        '1' => [
            'start_external_id' => 'IDFM:PUBLIC:71517',
            'end_external_ids' => ['IDFM:PUBLIC:71634'],
            'start_name' => 'La Défense',
            'end_names' => ['Château de Vincennes'],
            'type' => 'simple',
        ],
        '2' => [
            'start_external_id' => 'IDFM:PUBLIC:474152',
            'end_external_ids' => ['IDFM:PUBLIC:71673'],
            'start_name' => 'Porte Dauphine',
            'end_names' => ['Nation'],
            'type' => 'simple',
        ],
        '3' => [
            'start_external_id' => 'IDFM:PUBLIC:72057',
            'end_external_ids' => ['IDFM:PUBLIC:71817'],
            'start_name' => 'Pont de Levallois - Bécon',
            'end_names' => ['Gallieni'],
            'type' => 'simple',
        ],
        '4' => [
            'start_external_id' => 'IDFM:PUBLIC:478883',
            'end_external_ids' => ['IDFM:PUBLIC:483315'],
            'start_name' => 'Porte de Clignancourt',
            'end_names' => ['Bagneux - Lucie Aubrac'],
            'type' => 'simple',
        ],
        '5' => [
            'start_external_id' => 'IDFM:PUBLIC:72486',
            'end_external_ids' => ['IDFM:PUBLIC:71033'],
            'start_name' => 'Bobigny - Pablo Picasso',
            'end_names' => ['Place d\'Italie'],
            'type' => 'simple',
        ],
        '6' => [
            'start_external_id' => 'IDFM:PUBLIC:71347',
            'end_external_ids' => ['IDFM:PUBLIC:71673'],
            'start_name' => 'Charles de Gaulle - Étoile',
            'end_names' => ['Nation'],
            'type' => 'simple',
        ],
        '7' => [
            'start_external_id' => 'IDFM:PUBLIC:73696',
            'end_external_ids' => ['IDFM:PUBLIC:70488', 'IDFM:PUBLIC:70143'],
            'start_name' => 'La Courneuve - 8 Mai 1945',
            'end_names' => ['Mairie d\'Ivry', 'Villejuif - Louis Aragon'],
            'type' => 'branched',
        ],
        '7B' => [
            'start_external_id' => 'IDFM:PUBLIC:71407',
            'end_external_ids' => ['IDFM:PUBLIC:71911', 'IDFM:PUBLIC:71885'],
            'start_name' => 'Louis Blanc',
            'end_names' => ['Pré-Saint-Gervais', 'Place des Fêtes'],
            'type' => 'loop',
        ],
        '8' => [
            'start_external_id' => 'IDFM:PUBLIC:71073',
            'end_external_ids' => ['IDFM:PUBLIC:69884'],
            'start_name' => 'Balard',
            'end_names' => ['Pointe du Lac'],
            'type' => 'simple',
        ],
        '9' => [
            'start_external_id' => 'IDFM:PUBLIC:70698',
            'end_external_ids' => ['IDFM:PUBLIC:71785'],
            'start_name' => 'Pont de Sèvres',
            'end_names' => ['Mairie de Montreuil'],
            'type' => 'simple',
        ],
        '10' => [
            'start_external_id' => 'IDFM:PUBLIC:70721',
            'start_external_ids' => ['IDFM:PUBLIC:70721', 'IDFM:PUBLIC:71169'],
            'end_external_ids' => ['IDFM:PUBLIC:71135'],
            'start_name' => 'Boulogne Pont de Saint-Cloud',
            'start_names' => ['Boulogne Pont de Saint-Cloud', 'Porte d\'Auteuil'],
            'end_names' => ['Gare d\'Austerlitz'],
            'type' => 'partial-loop',
        ],
        '11' => [
            'start_external_id' => 'IDFM:PUBLIC:71264',
            'end_external_ids' => ['IDFM:PUBLIC:426280'],
            'start_name' => 'Châtelet',
            'end_names' => ['Rosny-Bois-Perrier'],
            'type' => 'simple',
        ],
        '12' => [
            'start_external_id' => 'IDFM:PUBLIC:72524',
            'end_external_ids' => ['IDFM:PUBLIC:70671'],
            'start_name' => 'Mairie d\'Aubervilliers',
            'end_names' => ['Mairie d\'Issy'],
            'type' => 'simple',
        ],
        '13' => [
            'start_external_id' => 'IDFM:PUBLIC:72358',
            'start_external_ids' => ['IDFM:PUBLIC:72358', 'IDFM:PUBLIC:72286'],
            'end_external_ids' => ['IDFM:PUBLIC:461505'],
            'start_name' => 'Saint-Denis - Université',
            'start_names' => ['Saint-Denis - Université', 'Asnières - Gennevilliers - Les Courtilles'],
            'end_names' => ['Châtillon - Montrouge'],
            'type' => 'branched',
        ],
        '14' => [
            'start_external_id' => 'IDFM:PUBLIC:490784',
            'end_external_ids' => ['IDFM:PUBLIC:63284'],
            'start_name' => 'Saint-Denis - Pleyel',
            'end_names' => ['Aéroport d\'Orly'],
            'type' => 'simple',
        ],
    ],
];
